# Generated by Django 3.1 on 2021-01-29 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='star',
        ),
        migrations.DeleteModel(
            name='StarRating',
        ),
    ]
