# Generated by Django 3.1 on 2021-01-29 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0003_wishproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishproduct',
            name='customer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='wish_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
